### ISSUE TITLE
dotnet consolidate fails immediately

### ISSUE THREAD

**Issue by ITDancer13** [olsh/dotnet-consolidate#36]
Version 4.0.0 of dotnet consolidate does not run anymore. The following exception is thrown immediately: 

```
Unhandled exception. System.MissingMethodException: Cannot dynamically create an instance of type 'DotNet.Consolidate.Models.Options'. Reason: No parameterless constructor defined.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at CommandLine.Core.InstanceBuilder.<>c__1`1.<Build>b__1_0(Func`1 f)
   at CSharpx.MaybeExtensions.MapValueOrDefault[T1,T2](Maybe`1 maybe, Func`2 func, T2 noneValue)
   at CommandLine.Core.InstanceBuilder.Build[T](Maybe`1 factory, Func`3 tokenizer, IEnumerable`1 arguments, StringComparer nameComparer, Boolean ignoreValueCase, CultureInfo parsin
gCulture, Boolean autoHelp, Boolean autoVersion, Boolean allowMultiInstance, IEnumerable`1 nonFatalErrors)
   at CommandLine.Parser.ParseArguments[T](IEnumerable`1 args)
   at DotNet.Consolidate.Program.Main(String[] args) in C:\projects\dotnet-consolidate\src\DotNet.Consolidate\Program.cs:line 26
```

How to reproduce:

- Create new Console Application with solution file
- run dotnet consolildate

Version 3.0.2 works as expected:
![image](https://github.com/olsh/dotnet-consolidate/assets/11077626/74cc29b0-9108-41aa-b47a-029a30b825fe)

**Comment by olsh** [comment]
@ITDancer13 thank you for letting me know.
The fixed version (4.0.1) will be published soon.
