### ISSUE TITLE
Exception occurres if using 1.2.0

### ISSUE THREAD

**Issue by xp-development** [olsh/dotnet-consolidate#4]
Since pull request #3 there is an exception while executing dotnet-consolidate.

```
##[error]Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at DotNet.Consolidate.Program.Consolidate(Options options) in C:\projects\dotnet-consolidate\src\DotNet.Consolidate\Program.cs:line 45
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at DotNet.Consolidate.Program.Main(String[] args) in C:\projects\dotnet-consolidate\src\DotNet.Consolidate\Program.cs:line 25
```

**Comment by olsh** [comment]
The issue was fixed in the 1.2.1 version.
Feel free to re-open the issue if you still get the error.
Thank you.
